// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<AppCore>>
abstract class AppCore implements RustOpaqueInterface {
  Future<void> indexText({required String text});

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<AppCore> newInstance(
          {required String dbPath, required String vectorDbPath}) =>
      RustLib.instance.api
          .crateApiSimpleAppCoreNew(dbPath: dbPath, vectorDbPath: vectorDbPath);

  Future<List<SearchResult>> searchText(
      {required String query, required BigInt limit});
}

class SearchResult {
  final int id;
  final String text;
  final double score;

  const SearchResult({
    required this.id,
    required this.text,
    required this.score,
  });

  @override
  int get hashCode => id.hashCode ^ text.hashCode ^ score.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SearchResult &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          text == other.text &&
          score == other.score;
}
